name: Release APK from Tag
on:
  push:
    tags: ['*']

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    env:
      PUB_CACHE: .pub-cache
      GRADLE_USER_HOME: ${{ github.workspace }}/android/.gradle
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '11.x'
      - name: Setup flutter
        uses: subosito/flutter-action@v1.3.2
        with:
          flutter-version: '1.17.5'
          channel: stable
      - name: Caching
        uses: actions/cache@v2
        with:
          path: |
            .pub-cache
            .dart_tool
            .flutter-plugins
            .flutter-plugins-dependencies
            android/.gradle
            build
          key: ${{ runner.os }}-build-caches
      - run: flutter pub upgrade
      - run: flutter build apk --verbose
      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: build/app/outputs/apk/release

  release:
    name: Release APK
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: build
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v2
        with:
          name: APK
          path: release_apk
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release_apk/app-release.apk
          asset_name: app-${{ github.ref }}-release.apk
          asset_content_type: application/vnd.android.package-archive
